### ISSUE TITLE
[Feature] Support more than one PC per campaign

### ISSUE THREAD

**Issue by posita** [nboughton/stargazer#19]
Currently, it appears that only one PC can exist in a campaign. Consider allowing a secretary to keep track of multiplayer campaigns by supporting more than one character in a campaign. I realize this can be "accommodated" (albeit clumsily) by tracking more than one campaign (using the other n-1 campaigns exclusively to track PCs), but there are games where multiple characters share Truths, sectors, etc.

**Comment by nboughton** [comment]
I'm afraid this falls outside the design goals of Stargazer. Stargazer is designed purely for solo play. For co-op or guided campaigns players should use a proper VTT like Roll20 or Foundry.

**Comment by posita** [comment]
Sorry if I was unclear. The feature request was to support *at-the-table* play with more than one *character* (possibly, but not necessarily involving more than one *player*). The services you suggest seem to be overkill for such an environment. However, I understand that you do not wish for this tool to be used for supporting more than a single character. Thanks for your consideration.
